name: CI/CD Pipeline for ShoppingWeb Application

on:
  push:
    branches:
      - master

jobs:
  # [1] Compilación
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Compile Code
        run: mvn clean compile

  # [2] Ejecución de Pruebas Unitarias
  unit-tests:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run Unit Tests
        run: mvn test -Dtest=com.example.simplewebapp.ShoppingServiceTests

  # [3] Packaging
  package:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Package Application
        run: mvn install -DskipTests

  # [4] Despliegue de la aplicación para pruebas
  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Start Application
        run: |
          java -jar target/simple-java-webapp-0.0.1-SNAPSHOT.jar &
          sleep 15 # Espera para que el servidor embebido de Spring Boot esté completamente iniciado

      - name: Test Connectivity
        run: |
          ping -c 10 localhost

  # [5] Ejecución de pruebas de interfaz de usuario con Selenium
  selenium-tests:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Chrome for Selenium
        uses: browser-actions/setup-chrome@v1

      - name: Run Selenium Tests
        run: |
          mvn test -Dtest=com.example.simplewebapp.selenium.ShoppingWebTests